inherit_from: "configs/rgbd/endomapper/base_config.yaml"

Dataset:
  dataset_path: "/root/GS_datasets/datasets/endomapper/endomapper_seq1/"
  Calibration:
    fx: 472.64955100886374 #391.886 第一个点的焦距，后面每一个其实都不一样，并且camera只给了一个值，这里先默认fx fy一样的值
    fy: 472.64955100886374 #391.886
    cx: 479.5
    cy: 359.5
    k1: 0 #？
    k2: 0 #？
    p1: 0 #？
    p2: 0 #？
    k3: 0 #？
    width: 960
    height: 720
    depth_scale: 5000.0
    distorted: False



